### ISSUE TITLE
Structure

### ISSUE THREAD

**Issue by RichardLitt** [nodeschool/bali#10]
I thought this was going to be more like workshoppers - basically, we just set people up with the workshoppers and have them work individually. However, the README has this: 

> Introduction to NodeJS;
> Resources and development using Node;
> About nodeschool and what it has to offer;
> Networking session and short presentations of some local nodeJS projects.

Which is it? Maybe we could do a combination - I think that the first two are covered by the workshoppers, and mean that we don't have to prepare a long talk about anything. The third we could throw in briefly - basically, describing how nodeschool works at the beginning, and how we plan to continue. Nodeschool isn't quite the same as a meet up - it's more like a learning session. I think having a short presentation // networking session would be good, maybe at the beginning, though. 

What do you think? Did you have a different view of this, @LaughingSun?

**Comment by LaughingSun** [comment]
I just through in some basic items that seemed important to include.  I am
not sure what you mean about meetup, you mean meetup.com?  I have no
expectations really.  If there is a suggested format already in use I would
just assume follow that as try to go out on our own limb, at least not
until there is some reason to.

Like you said some is covered in workshoppers, so I was right.  But what is
your vision here?

Basically until I see there are people coming, my efforts will be mostly to
promote.  As people get involved organically the school will evolve.

You obviously have some experience running these, yes?

On Tue, Mar 24, 2015 at 12:37 PM, Richard Littauer <notifications@github.com

> wrote:
> 
> I thought this was going to be more like workshoppers - basically, we just
> set people up with the workshoppers and have them work individually.
> However, the README has this:
> 
> Introduction to NodeJS;
> Resources and development using Node;
> About nodeschool and what it has to offer;
> Networking session and short presentations of some local nodeJS projects.
> 
> Which is it? Maybe we could do a combination - I think that the first two
> are covered by the workshoppers, and mean that we don't have to prepare a
> long talk about anything. The third we could throw in briefly - basically,
> describing how nodeschool works at the beginning, and how we plan to
> continue. Nodeschool isn't quite the same as a meet up - it's more like a
> learning session. I think having a short presentation // networking session
> would be good, maybe at the beginning, though.
> 
> What do you think? Did you have a different view of this, @LaughingSun
> https://github.com/LaughingSun?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nodeschool/bali/issues/10.

## 

Erich Horn
Denpasar, Bali, Indonesia
(62) 82140467070

**Comment by RichardLitt** [comment]
Ah, cool. Yeah, by meetup I mean more of a structured event - the other Nodeschools I've been to have all been just people in a room doing workshoppers, with mentors around in case they need help. So, no presentations or talks. I was just thinking we introduce ourselves, explain this is how Nodeschool works, how to get on the site and download the workshoppers, and then ask people to start hacking. So, really, the whole work is just promotion, nothing else.

**Comment by RichardLitt** [comment]
I helped out at the SF Nodeschool last month. Was fun.

**Comment by RichardLitt** [comment]
People are coming! I expect around 20 people at the moment, and I have a translator. Let's start with workshoppers and plan for other things while we're there. Extemporaneous! :)

**Comment by LaughingSun** [comment]
yes, it is great. I will be back in a few hours. and prepare anything I
missed so far.

On Fri, Apr 3, 2015 at 2:32 PM, Richard Littauer notifications@github.com
wrote:

> Closed #10 https://github.com/nodeschool/bali/issues/10.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nodeschool/bali/issues/10#event-272435858.

## 

Erich Horn
Denpasar, Bali, Indonesia
(62) 82140467070
