### ISSUE TITLE
Add links to Homepage

### ISSUE THREAD

**Issue by RichardLitt** [nodeschool/bali#11]
Event details! 

http://www.hubud.org/event/nodeschool-bali/
https://www.facebook.com/events/842595932480538/

**Comment by seacgroup** [comment]
well I shared it on all my appropriate groups and sent emails to the people I know here who might be interested.  I also sent to Nick Martin and a few others running incubators.  Looks like we have good interest starting quickly.

**Comment by RichardLitt** [comment]
Nice.

**Comment by RichardLitt** [comment]
Added in links in 40a9c06
