### ISSUE TITLE
Next meeting

### ISSUE THREAD

**Issue by LaughingSun** [nodeschool/bali#2]
Hey everyone,

I would love to do a follow-up meetup quite soon. Maybe even start something recurring like they are doing in Jakarta right now.

Let's collect ideas here when and where to do this.

Best,
Erich

**Comment by RichardLitt** [comment]
How about an event in Ubud at the end of March // early April?

**Comment by RichardLitt** [comment]
I can find a space for us in Hubud, most likely. I'll start looking into rooms. @LaughingSun, you in?

Anyone else?

**Comment by LaughingSun** [comment]
Great Richard, lets get this started.  And sorry for the late reply, I have
been busy on my other projects for the last few weeks. Lets talk soon.

On Mon, Mar 2, 2015 at 2:44 AM, Richard Littauer notifications@github.com
wrote:

> I can find a space for us in Hubud, most likely. I'll start looking into
> rooms. @LaughingSun https://github.com/LaughingSun, you in?
> 
> Anyone else?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nodeschool/bali/issues/2#issuecomment-76623395.

## 

Erich Horn
Denpasar, Bali, Indonesia
(62) 82140467070

**Comment by RichardLitt** [comment]
No problem! I've emailed Hubud to ask for a space, and they've been in contact on Twitter, so that should work well, actually. I'm waiting to hear back from them about time // space, but should be good. Does that work for you?

**Comment by LaughingSun** [comment]
sounds excellent.  Can I add you to the Bali nodeschool contributors list?

On Sun, Mar 8, 2015 at 6:38 AM, Richard Littauer notifications@github.com
wrote:

> No problem! I've emailed Hubud to ask for a space, and they've been in
> contact on Twitter, so that should work well, actually. I'm waiting to hear
> back from them about time // space, but should be good. Does that work for
> you?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nodeschool/bali/issues/2#issuecomment-77714459.

## 

Erich Horn
Denpasar, Bali, Indonesia
(62) 82140467070

**Comment by RichardLitt** [comment]
I'm part of Nodeschool already; I just accepted my PR for English changes, so I should be a contributor to this particular repo now. 

Regarding the event; I was thinking we just have an afternoon or so where people can work on the workshoppers, and we can hang around as mentors and help with any questions if people have them. What do you think?

**Comment by LaughingSun** [comment]
yeah that is all good.  What we need is Bahasa and / or Balinese
translations.  Know anyone?  Maybe we can find someone during the
workshop.  Thanks.

On Sun, Mar 8, 2015 at 7:45 AM, Richard Littauer notifications@github.com
wrote:

> I'm part of Nodeschool already; I just accepted my PR for English changes,
> so I should be a contributor to this particular repo now.
> 
> Regarding the event; I was thinking we just have an afternoon or so where
> people can work on the workshoppers, and we can hang around as mentors and
> help with any questions if people have them. What do you think?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nodeschool/bali/issues/2#issuecomment-77719150.

## 

Erich Horn
Denpasar, Bali, Indonesia
(62) 82140467070

**Comment by RichardLitt** [comment]
I don't know anyone. :/ I don't speak Bahasa, either.

**Comment by LaughingSun** [comment]
Well I speak and understand simple bahasa Indonesia, but not well enough to
do a presentation or workshop in Indonesian.  I am sure someone will step
forward.  Let me knwo when you hear from hubud.  I was wondering what you
know about livit.  That might be another option. I wil lstart looking at
options if you don't hear back from the hubud people.

On Sun, Mar 8, 2015 at 9:32 AM, Richard Littauer notifications@github.com
wrote:

> I don't know anyone. :/ I don't speak Bahasa, either.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nodeschool/bali/issues/2#issuecomment-77727075.

## 

Erich Horn
Denpasar, Bali, Indonesia
(62) 82140467070

**Comment by RichardLitt** [comment]
Alright, Hubud got back to me and we're working on getting a space. Here's the email I sent - sound good, @LaughingSun?

> So, I would need to know if there is a room large enough to host 20-30 people. I would expect around that much to show up, but we won't know until I set up an event somewhere. What is your largest room, perhaps? Would you charge us for using it? 
> 
> I need to know if you would be OK with people who are not paying members of Ubud joining for the duration of the session. The session could run for 2-3 hours, or all day; I think somewhere in between would be best, perhaps from 12-5. 
> 
> Finally, I would need to know if anyone there is interested in helping out with Bahasa translations and/or support for native Bahasa speakers. I don't want this to be an English only event, but we can see how it goes. 
> 
> The formatting is fairly simple; get people in a room with wifi and chairs and tables. I'll stand up, say welcome to node school, go over the workshoppers (basically, downloadable tutorials) that people should start in, and then offer to help mentor if anyone needs help. Hopefully, if there are more Node experts around, they'd be happy to volunteer to help, as well. Then people go through the workshoppers at their own pace, and at some point we take a picture for the event, point to more Node resources for further self study, and call it a day, and then probably go out for dinner or something. Sound clear?

**Comment by LaughingSun** [comment]
Yes we can pursue this.  Be aware that this group is very new and while I
did do some promotion in the beginning my current obligations have
temporarily forced me to remove my time resources from the group, as such
there are nearly zero members.  Just the same I am sure there is much
interest, once we get a date we can both publicize it.  I am sure I know at
least 5 people who would be interested and would show assuming they are
available.

I would suggest 2 to 3 forty minute sessions with 10 - 20 minute breaks in
between.which would be used for micro assignments, bathroom breaks and
socializing.

I am really happy to have your initiative on this, and will likely support
any of your efforts.  A few more people like the 2 of us and I think we
might actually have an active group.

Keep me posted.  You may also reach me at 082140467070 by sms.

Regards

On Fri, Mar 13, 2015 at 3:38 AM, Richard Littauer notifications@github.com
wrote:

> Alright, Hubud got back to me and we're working on getting a space. Here's
> the email I sent - sound good, @LaughingSun
> https://github.com/LaughingSun?
> 
> So, I would need to know if there is a room large enough to host 20-30
> people. I would expect around that much to show up, but we won't know until
> I set up an event somewhere. What is your largest room, perhaps? Would you
> charge us for using it?
> 
> I need to know if you would be OK with people who are not paying members
> of Ubud joining for the duration of the session. The session could run for
> 2-3 hours, or all day; I think somewhere in between would be best, perhaps
> from 12-5.
> 
> Finally, I would need to know if anyone there is interested in helping out
> with Bahasa translations and/or support for native Bahasa speakers. I don't
> want this to be an English only event, but we can see how it goes.
> 
> The formatting is fairly simple; get people in a room with wifi and chairs
> and tables. I'll stand up, say welcome to node school, go over the
> workshoppers (basically, downloadable tutorials) that people should start
> in, and then offer to help mentor if anyone needs help. Hopefully, if there
> are more Node experts around, they'd be happy to volunteer to help, as
> well. Then people go through the workshoppers at their own pace, and at
> some point we take a picture for the event, point to more Node resources
> for further self study, and call it a day, and then probably go out for
> dinner or something. Sound clear?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nodeschool/bali/issues/2#issuecomment-78586825.

## 

Erich Horn
Denpasar, Bali, Indonesia
(62) 82140467070

**Comment by RichardLitt** [comment]
New is fine! Hubud got back to me - I suggested the 4th. Does that work for you? I'm sure there will be some people there who want to join in, too. I won't be able to commit to more than this one-shot; I'm heading off to Thailand on the 16th, so --- let's make this work. :) 

2-3 40 minutes sounds good. I'll let you know my SMS when I get there - in the SFO airport at the moment.

**Comment by LaughingSun** [comment]
The forth is good.  Btw, do you know about Nyepi, the day of silence?  That
is the 21st, just a few days away.  You cannot get out or around on that
day, so make sure you have a good spot to camp out (figuratively speaking)
with lots provisions.

ok have a good flight.  Yeah I grew up in Berkeley, most of my career has
been in the SF Bay Area or Singapore.  My second favorite place in the
world is San Francisco.  But I always miss Indonesia when I am back there.
 :)  See you soon.

On Thu, Mar 19, 2015 at 3:11 PM, Richard Littauer notifications@github.com
wrote:

> New is fine! Hubud got back to me - I suggested the 4th. Does that work
> for you? I'm sure there will be some people there who want to join in, too.
> I won't be able to commit to more than this one-shot; I'm heading off to
> Thailand on the 16th, so --- let's make this work. :)
> 
> 2-3 40 minutes sounds good. I'll let you know my SMS when I get there - in
> the SFO airport at the moment.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nodeschool/bali/issues/2#issuecomment-83376191.

## 

Erich Horn
Denpasar, Bali, Indonesia
(62) 82140467070

**Comment by RichardLitt** [comment]
Yeah, looking forward to Nyepi - going to be a good excuse to chill out and code all day. :) Got here today, glad I'll be able to get over jet lag appropriately. Cool that you're also familiar with the bay area - this should be fun!

**Comment by LaughingSun** [comment]
Richard, I was going to post the event, but I don't have the complete
details.  Can you send me the date/time and venue details so I can add to
the post?  Thanks.

On Fri, Mar 20, 2015 at 8:45 PM, Richard Littauer notifications@github.com
wrote:

> Yeah, looking forward to Nyepi - going to be a good excuse to chill out
> and code all day. :) Got here today, glad I'll be able to get over jet lag
> appropriately. Cool that you're also familiar with the bay area - this
> should be fun!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nodeschool/bali/issues/2#issuecomment-84005020.

## 

Erich Horn
Denpasar, Bali, Indonesia
(62) 82140467070

**Comment by RichardLitt** [comment]
@LaughingSun Just sat down and talked to Vitto, the guy here at Hubud. Looks like the 5th from 2-6pm will work best for them and me (I can't do the 4th, I learned yesterday). Does that work for you?

**Comment by LaughingSun** [comment]
that is a sunday yes?  Seems good. please confirm it.

On Mon, Mar 23, 2015 at 11:22 AM, Richard Littauer <notifications@github.com

> wrote:
> 
> @LaughingSun https://github.com/LaughingSun Just sat down and talked to
> Vitto, the guy here at Hubud. Looks like the 5th from 2-6pm will work best
> for them and me (I can't do the 4th, I learned yesterday). Does that work
> for you?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nodeschool/bali/issues/2#issuecomment-84775586.

## 

Erich Horn
Denpasar, Bali, Indonesia
(62) 82140467070

**Comment by RichardLitt** [comment]
Sunday, yep! In that case, we're a go!

**Comment by RichardLitt** [comment]
The event will take place on Sunday, April 5th. It will be held at the Living Food Lab area of Hubud from 2pm - 6pm.

**Comment by krisnaw** [comment]
Hello, 

I wanna join

By the way how many participant till date?

**Comment by RichardLitt** [comment]
I think like 15 are coming; I really need to update the page! Details here: https://www.facebook.com/events/842595932480538/

**Comment by krisnaw** [comment]
It's open for everyone?
Maybe I can make it in Bahasa Indonesia so hopefully a lot local people will came

**Comment by RichardLitt** [comment]
Yeah, it is! We have a guy to help translate, too - would be awesome if we could hack together some Bahasa translations for the workshoppers, and if people who are local come. Please!

**Comment by reeouw** [comment]
when will it be hold?
I'd love to join this event
