### ISSUE TITLE
Blurb for social media

### ISSUE THREAD

**Issue by RichardLitt** [nodeschool/bali#9]

**Comment by RichardLitt** [comment]
Hubud wants a blurb for Facebook and the like, so that they can describe it. What do you think, @LaughingSun?

**Comment by LaughingSun** [comment]
yes I also want that as well!  :)

On Tue, Mar 24, 2015 at 12:32 PM, Richard Littauer <notifications@github.com

> wrote:
> 
> Hubud wants a blurb for Facebook and the like, so that they can describe
> it. What do you think, @LaughingSun https://github.com/LaughingSun?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nodeschool/bali/issues/9#issuecomment-85335254.

## 

Erich Horn
Denpasar, Bali, Indonesia
(62) 82140467070
